backend:
  name: github
  repo: taylorazizeh/website2.0
  branch: main
  base_url: https://taylor-decap-auth.taylorazizeh.workers.dev
  auth_endpoint: /auth

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Body"
        name: "body"
        widget: "markdown"
